# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

_SNAKE_TO_CAMEL_CASE_TABLE = {
    "attribute_friendly_name": "attributeFriendlyName",
    "attribute_name": "attributeName",
    "claim_name": "claimName",
    "client_id": "clientId",
    "client_secret": "clientSecret",
    "client_timeout": "clientTimeout",
    "identity_provider_alias": "identityProviderAlias",
    "initial_login": "initialLogin",
    "user_attribute": "userAttribute",
}

_CAMEL_TO_SNAKE_CASE_TABLE = {
    "attributeFriendlyName": "attribute_friendly_name",
    "attributeName": "attribute_name",
    "claimName": "claim_name",
    "clientId": "client_id",
    "clientSecret": "client_secret",
    "clientTimeout": "client_timeout",
    "identityProviderAlias": "identity_provider_alias",
    "initialLogin": "initial_login",
    "userAttribute": "user_attribute",
}
