// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
	"github.com/pulumi/pulumi/sdk/go/pulumi/config"
)

func GetClientId(ctx *pulumi.Context) string {
	return config.Get(ctx, "keycloak:clientId")
}

func GetClientSecret(ctx *pulumi.Context) string {
	return config.Get(ctx, "keycloak:clientSecret")
}

// Timeout (in seconds) of the Keycloak client
func GetClientTimeout(ctx *pulumi.Context) int {
	return config.GetInt(ctx, "keycloak:clientTimeout")
}

// Whether or not to login to Keycloak instance on provider initialization
func GetInitialLogin(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "keycloak:initialLogin")
}

func GetPassword(ctx *pulumi.Context) string {
	return config.Get(ctx, "keycloak:password")
}

func GetRealm(ctx *pulumi.Context) string {
	return config.Get(ctx, "keycloak:realm")
}

// The base URL of the Keycloak instance, before `/auth`
func GetUrl(ctx *pulumi.Context) string {
	return config.Get(ctx, "keycloak:url")
}

func GetUsername(ctx *pulumi.Context) string {
	return config.Get(ctx, "keycloak:username")
}
